# Uptycs enroll secret & nginx certs are stack specific & are required to communitcate with Uptycs cloud service.
# Enroll secret contains customer identifiers & should match with allowed Uptycs infra config.
# Nginx secret contains all the root CA's accepted by Uptycs cloud.
apiVersion: v1
kind: Secret
metadata:
  name: uptycs-secret
  namespace: uptycs
  labels:
    app.kubernetes.io/name: uptycs-secret
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
type: Opaque
stringData:
  uptycs.secret: __UPTYCS_SECRET__
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: uptycs
type: Opaque
stringData:
  ca.crt: |
    __NGINX_SECRET__
