# Uptycs Osquery flags file contents
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: uptycs-config
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
data:
{{- if .Values.configmap.data.osquery_tags }}
  osquery.tags: |
{{ .Values.configmap.data.osquery_tags | trim | indent 4 }}
{{- end }}
  osquery.flags: |
{{ .Values.configmap.data.osquery | indent 4 }}
