# Uptycs Osquery flags file contents

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  {{- include "k8sosquery.namespace" . }}
  labels:
    app.kubernetes.io/name: uptycs-config
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
data:
{{- if .Values.configmap.data.tags }}
  osquery.tags: |
{{ .Values.configmap.data.tags | trim | indent 4 }}
{{- end }}
{{- if .Values.configmap.data.local_proxy }}
  osquery.local_proxy: |
{{ .Values.configmap.data.local_proxy | trim | indent 4 }}
{{- end }}
  osquery.flags: |
{{ .Values.configmap.data.osquery | indent 4 }}
