{{- if .Values.isGKEAutopilot }}
apiVersion: auto.gke.io/v1
kind: AllowlistSynchronizer
metadata:
  name: uptycs-runtime-sensor-v1.0.0
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  allowlistPaths:
  - Uptycs/uptycs-runtime-sensor/uptycs-runtime-sensor-v1.0.0.yaml  
{{- end }}