{{- if ne .Release.Namespace "default"}}
{{- else if not (lookup "v1" "Namespace" "" ".Values.namespace" ) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: uptycs
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
{{- end }}
