# Create nginx secret
{{- if .Values.secrets.createNginxSecret }}
{{- $namespaceYaml := include "k8sosquery.namespace" . }}
{{- $nsObj := $namespaceYaml | fromYaml }}
{{- $namespace := $nsObj.namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  {{- include "k8sosquery.namespace" . }}
  {{- include "k8sosquery.commonLabels" . }}
  {{- include "k8sosquery.commonAnnotations" . }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.secrets.nginx_secret | indent 4 }}
{{- end }}