# Create nginx secret
{{- if .Values.secrets.createNginxSecret }}
{{- $namespaceYaml := include "k8sosquery.namespace" . }}
{{- $nsObj := $namespaceYaml | fromYaml }}
{{- $namespace := $nsObj.namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  {{- include "k8sosquery.namespace" . }}
  {{- with .Values.commonLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.secrets.nginx_secret | indent 4 }}
{{- end }}