# Create SecurityContextConstraints for uptycs-osquery service account
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: uptycs-osquery-privileged
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
  labels:
    app.kubernetes.io/name: uptycs-osquery-privileged
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
readOnlyRootFilesystem: false
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:{{ .Values.namespace.name }}:uptycs-osquery
volumes:
- '*'
{{- end }}
