# Create service account for uptycs osquery daemonset
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptycs-osquery
  {{- include "k8sosquery.namespace" . }}
  labels:
    app.kubernetes.io/name: uptycs-osquery
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
    app.kubernetes.io/version: 1.0.0 
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.daemonset.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.daemonset.imagePullSecrets }}
{{- end }}
