# Create service account for uptycs osquery daemonset
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptycs-osquery
  {{- include "k8sosquery.namespace" . }}
{{- if .Values.daemonset.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.daemonset.imagePullSecrets }}
{{- end }}
