# Create secret for Uptycs shared secret. This will be made available to all daemonset pods
apiVersion: v1
kind: Secret
metadata:
  name: uptycs-secret
  {{- include "k8sosquery.namespace" . }}
  labels:
    app.kubernetes.io/name: uptycs-secret
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
type: Opaque
stringData:
  uptycs.secret: {{ .Values.secrets.enroll_secret }}
