# Uptycs enroll secret & nginx certs are stack specific & are required to communitcate with Uptycs cloud service.
# Enroll secret contains customer identifiers & should match with allowed Uptycs infra config.
# Nginx secret contains all the root CA's accepted by Uptycs cloud.
# Webhook Server TLS secret is used by Kubequery admission controllers to setup the HTTPS endpoints.
# These endpoints are then called by K8s API server during resource admission.
# All three secrets are created in "kubequery" namespace.
apiVersion: v1
kind: Secret
metadata:
  name: enroll.secret
  namespace: kubequery
type: Opaque
stringData:
  enroll.secret: __UPTYCS_ENROLL_SECRET__
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: kubequery
type: Opaque
stringData:
  ca.crt: |
    __UPTYCS_NGINX_CRT__
---
apiVersion: v1
data:
  tls.crt: __UPTYCS_WEBHOOK_SERVER_TLS_CRT__
  tls.key: __UPTYCS_WEBHOOK_SERVER_TLS_KEY__
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: kubequery
type: kubernetes.io/tls
