# Uptycs enroll secret & nginx certs are stack specific & are required to communitcate with Uptycs cloud service.
# Enroll secret contains customer identifiers & should match with allowed Uptycs infra config.
# Nginx secret contains all the root CA's accepted by Uptycs cloud.
# Both the secrets are created in "kubequery" namespace.
apiVersion: v1
kind: Secret
metadata:
  name: enroll.secret
  namespace: kubequery
type: Opaque
stringData:
  enroll.secret: __UPTYCS_ENROLL_SECRET__
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: kubequery
type: Opaque
stringData:
  ca.crt: |
    __UPTYCS_NGINX_CRT__
