{{- if not .Values.auditLogDetections.aks.disable_audit }}
apiVersion: v1
kind: Secret
metadata:
  name: eventhub.secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  eventhub.secret: {{ .Values.auditLogDetections.aks.aks_eventhub_secret }}
{{- end}}
