apiVersion: v1
kind: ConfigMap
metadata:
  name: kubequery-config
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  {{- include "kubequery.namespace" .}}
  {{- end }}
data:
  kubequery.flags: |-
{{- range $key, $value := .Values.admissionControllerParameters }}
  {{- if $value }}
    --{{ $key }}={{ $value }}
  {{- end }}
  {{- if not $value }}
    --{{ $key }}=false
  {{- end }}
{{- end }}
{{- if .Values.auditLogDetections.aks.disable_audit }}
    --disable_aks_audit={{ .Values.auditLogDetections.aks.disable_audit }}
{{- else }}
    --disable_aks_audit={{ .Values.auditLogDetections.aks.disable_audit }}
  {{- range $key, $value := .Values.auditLogDetections.aks }}
    {{- if $value }}
    --{{ $key }}={{ $value }}
    {{- end }}
  {{- end }}
    --aks_eventhub_key_path=/opt/uptycs/config/eventhub/eventhub.secret
{{- end }}
{{- if .Values.auditLogDetections.eks.disable_audit }}
    --disable_eks_audit={{ .Values.auditLogDetections.eks.disable_audit }}
{{- else }}
    --disable_eks_audit={{ .Values.auditLogDetections.eks.disable_audit }}
  {{- range $key, $value := .Values.auditLogDetections.eks }}
    {{- if $value }}
    --{{ $key }}={{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.auditLogDetections.gke.disable_audit }}
    --disable_gke_audit={{ .Values.auditLogDetections.gke.disable_audit }}
{{- else }}
    --disable_gke_audit={{ .Values.auditLogDetections.gke.disable_audit }}
  {{- range $key, $value := .Values.auditLogDetections.gke }}
    {{- if $value }}
    --{{ $key }}={{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
    --disable_unmanaged_cluster_audit={{ .Values.auditLogDetections.unmanaged_cluster.disable_audit }}
{{ .Values.configmap.data.kubequeryFlags | indent 4 }}
  kubequery.conf: |-
{{ .Values.configmap.data.kubequeryConf | indent 4 }}
