apiVersion: v1
kind: Secret
metadata:
  name: enroll.secret
  {{- include "kubequery.namespace" . }}
  {{- include "kubequery.commonLabels" . }}
  {{- include "kubequery.commonAnnotations" . }}
type: Opaque
stringData:
  enroll.secret: {{ .Values.secrets.enroll_secret }}
