{{- if not .Values.auditLogDetections.gke.disable_audit }}
apiVersion: v1
kind: Secret
metadata:
  name: gke.secret
  {{- include "kubequery.namespace" .}}
type: Opaque
data:
  gke.secret: {{ .Values.auditLogDetections.gke.gke_secret }}
{{- end}}
