{{- if not .Values.auditLogDetections.gke.disable_audit }}
apiVersion: v1
kind: Secret
metadata:
  name: gke.secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  gke.secret: {{ .Values.auditLogDetections.gke.gke_secret }}
{{- end}}
