{{- if not (lookup "v1" "Namespace" ""  .Values.namespace ) }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: cluster
    app.kubernetes.io/name: kubequery
    app.kubernetes.io/part-of: Uptycs
    app.kubernetes.io/version: "1.0.0"
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  name: {{ .Values.openshift.namespace.name }}
  {{- else }}
  name: {{ .Values.namespace }}
  {{- end }}
{{- end }}
