{{- if .Values.secrets.createNginxSecret }}
{{- $namespaceYaml := include "kubequery.namespace" . }}
{{- $nsObj := $namespaceYaml | fromYaml }}
{{- $namespace := $nsObj.namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  {{- include "kubequery.namespace" . }}
  {{- include "kubequery.commonLabels" . }}
  {{- include "kubequery.commonAnnotations" . }}
type: Opaque
stringData:
  ca.crt: {{ quote .Values.secrets.nginx_secret }}
{{- end }}