# Create SecurityContextConstraints for uptycs-kubequery service account
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubequery-sa
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
  labels:
    app.kubernetes.io/name: kubequery-sa
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: endpoint
    app.kubernetes.io/part-of: Uptycs
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
allowedUnsafeSysctls: []
readOnlyRootFilesystem: false
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles: []
users:
{{- if (ne .Release.Namespace "default") }}
- system:serviceaccount:{{ .Release.Namespace }}:kubequery-sa
{{- else }}
- system:serviceaccount:{{ .Values.openshift.namespace.name }}:kubequery-sa
{{- end }}
volumes:
- '*'
{{- end }}
