{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_image_admission_controller) -}}
apiVersion: v1
kind: Service
metadata:
  name: kubequery-webhook
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  ports:
    - port: 443
      targetPort: webhook-api
  selector:
    app: kubequery
{{- end}}
