apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubequery-sa
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  {{- include "kubequery.namespace" .}}
  {{- end }}
  {{- include "kubequery.sa.irsa" . }}
secrets:
  - name: webhook-server-tls
{{- if .Values.deployment.spec.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.deployment.spec.imagePullSecrets }}
{{- end }}
