{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_gatekeeper_controller) -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    gatekeeper.sh/system: "yes"
  name: kubequery-webhook-gatekeeper
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
spec:
  ports:
    - name: https-webhook-server
      port: 443
      targetPort: gk-webhook-api
  selector:
      app: kubequery
{{- end}}
