apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubequery-sa
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
secrets:
  - name: webhook-server-tls
