apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubequery-sa
  {{- include "kubequery.namespace" . }}
  {{- include "kubequery.sa.irsa" . }}
secrets:
  - name: webhook-server-tls
{{- if .Values.deployment.spec.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.deployment.spec.imagePullSecrets }}
{{- end }}
