{{ $cn := "" }}
{{ $extnames := "" }}
{{ if (ne .Release.Namespace  "default") }}
{{ $cn = print "*.kubequery-webhook." .Release.Namespace ".svc" }}
{{ $extnames = (list  (print "kubequery-webhook."  (toString  .Release.Namespace) ".svc")  (print "kubequery-webhook-gatekeeper."  (toString  .Release.Namespace) ".svc") "www.uptycs.com" ) }}
{{ else }}
{{ $cn = print "*.kubequery-webhook." .Values.namespace ".svc" }}
{{ $extnames = (list  (print "kubequery-webhook."  (toString  .Values.namespace) ".svc")  (print "kubequery-webhook-gatekeeper."  (toString  .Values.namespace) ".svc") "www.uptycs.com" ) }}
{{ end }} 
{{ $ca := genCA $cn 365 }}
{{ $cert := genSignedCert (include "kubequery.name" .)  nil $extnames 365 $ca }}
{{ $caBundle :=  b64enc $ca.Cert   -}}
---
apiVersion: v1
data:
  tls.crt: {{ b64enc $cert.Cert  }}
  tls.key: {{ b64enc $cert.Key }}
kind: Secret
metadata:
  name: webhook-server-tls
  {{- include "kubequery.namespace" . }}
type: kubernetes.io/tls
---
{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_gatekeeper_controller) -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    gatekeeper.sh/system: "yes"
  name: kubequery-webhook-gatekeeper
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: {{ $caBundle }}
      service:
        name: kubequery-webhook-gatekeeper
        {{- include "kubequery.namespace" . | indent 6 }}
        path: /v1/admit
    failurePolicy: Ignore
    matchPolicy: Exact
    {{- include "kubequery.gk.svc.name" . | indent 2 }}
    namespaceSelector:
      matchExpressions:
        - key: admission.gatekeeper.sh/ignore
          operator: DoesNotExist
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
    sideEffects: None
    timeoutSeconds: 3
{{- end}}
---
{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_image_admission_controller) -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubequery-webhook
webhooks:
  -
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $caBundle }}
      service:
        name: kubequery-webhook
        {{- include "kubequery.namespace" . | indent 6 }}
        path: /validate
    failurePolicy: Ignore
    sideEffects: None
    {{- include "kubequery.svc.name" . | indent 2 }}
    rules:
      - apiGroups:
          - ""
          - apps
        apiVersions:
          - v1beta1
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - jobs
          - cronjobs
        scope: "Namespaced"
    timeoutSeconds: 30
{{- end}}
