{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_image_admission_controller) -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubequery-webhook
webhooks:
  -
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ .Values.webhook.caBundle }}
      service:
        name: kubequery-webhook
        namespace: {{ .Values.namespace }}
        path: /validate
    failurePolicy: Ignore
    sideEffects: None
    name: kubequery-webhook.kubequery.svc
    rules:
      - apiGroups:
          - ""
          - apps
        apiVersions:
          - v1beta1
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - jobs
          - cronjobs
        scope: "Namespaced"
    timeoutSeconds: 30
{{- end}}
