{{ if and (not .Values.uptycsProtectDisabled) (not .Values.admissionControllerParameters.disable_gatekeeper_controller) -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    gatekeeper.sh/system: "yes"
  name: kubequery-webhook-gatekeeper
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: {{ .Values.webhook.caBundle }}
      service:
        name: kubequery-webhook-gatekeeper
        namespace: {{ .Values.namespace.name }}
        path: /v1/admit
    failurePolicy: Ignore
    matchPolicy: Exact
    name: kubequery-webhook-gatekeeper.kubequery.svc
    namespaceSelector:
      matchExpressions:
        - key: admission.gatekeeper.sh/ignore
          operator: DoesNotExist
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
    sideEffects: None
    timeoutSeconds: 3
{{- end}}
