apiVersion: v1
data:
  tls.crt: {{ .Values.webhookServerTLS.crt }}
  tls.key: {{ .Values.webhookServerTLS.key }}
kind: Secret
metadata:
  name: webhook-server-tls
  {{- if .Capabilities.APIVersions.Has "config.openshift.io/v1" }}
  namespace: {{ .Values.openshift.namespace.name }}
  {{- else }}
  {{- include "kubequery.namespace" . }}
  {{- end }}
type: kubernetes.io/tls
